openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the Retrieval-Augmented Generation chatbot integrated with AI-powered textbook
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

paths:
  /chat/query:
    post:
      summary: Submit a question to the RAG chatbot
      description: Retrieves relevant textbook content and generates a response based on the question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatQueryRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatQueryResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: No relevant context found - response refused
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefusalResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /chat/selected-text:
    post:
      summary: Submit a question with selected text context
      description: Uses only the provided selected text as context for the LLM, bypassing vector database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SelectedTextQueryRequest'
      responses:
        '200':
          description: Successful response from the chatbot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatQueryResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: No answer could be derived from the selected text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefusalResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Check the health of the service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ChatQueryRequest:
      type: object
      required:
        - question
        - session_id
      properties:
        question:
          type: string
          description: The question to ask the chatbot
          example: "What are the key principles of neural networks?"
        session_id:
          type: string
          format: uuid
          description: Unique identifier for the chat session
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        context:
          type: object
          description: Additional context for the query
          properties:
            chapter:
              type: string
              description: Specific chapter to focus on (optional)
              example: "Chapter 5"
            section:
              type: string
              description: Specific section to focus on (optional)
              example: "5.2 Backpropagation"

    SelectedTextQueryRequest:
      type: object
      required:
        - question
        - selected_text
        - session_id
      properties:
        question:
          type: string
          description: The question to ask about the selected text
          example: "Can you explain this concept?"
        selected_text:
          type: string
          description: The text that the user has selected/highlighted
          example: "Backpropagation is a method used in artificial neural networks to calculate the gradient of the loss function with respect to the weights."
        session_id:
          type: string
          format: uuid
          description: Unique identifier for the chat session
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"

    ChatQueryResponse:
      type: object
      required:
        - response
        - confidence
        - retrieved_chunks
        - session_id
      properties:
        response:
          type: string
          description: The chatbot's response to the question
          example: "Neural networks are computing systems inspired by the human brain..."
        confidence:
          type: number
          format: float
          description: Confidence level of the response (0.0 to 1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.92
        retrieved_chunks:
          type: array
          description: Metadata for the chunks used to generate the response
          items:
            $ref: '#/components/schemas/ChunkMetadata'
        sources:
          type: array
          description: List of sources referenced in the response
          items:
            type: string
            description: Source identifier
            example: "Chapter 3, Section 3.2"
        session_id:
          type: string
          format: uuid
          description: Unique identifier for the chat session
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        query_type:
          type: string
          description: Type of query that was processed
          enum: [general, selected_text]
          example: "general"

    RefusalResponse:
      type: object
      required:
        - message
        - reason
        - session_id
      properties:
        message:
          type: string
          description: The refusal message to display to the user
          example: "I cannot answer this question as it's not covered in the provided textbook content."
        reason:
          type: string
          description: The reason for refusing the answer
          enum: [no_context_found, insufficient_context, context_not_applicable, selected_text_insufficient]
          example: "no_context_found"
        session_id:
          type: string
          format: uuid
          description: Unique identifier for the chat session
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"

    ChunkMetadata:
      type: object
      properties:
        chunk_id:
          type: string
          description: Unique identifier for the content chunk
          example: "chunk-001-abc123"
        chapter:
          type: string
          description: Chapter name or identifier
          example: "Chapter 5"
        section:
          type: string
          description: Section name or identifier
          example: "5.2 Backpropagation"
        page_number:
          type: integer
          description: Page number in the textbook
          example: 127
        text_preview:
          type: string
          description: Short preview of the text content
          example: "Backpropagation is a method used in artificial neural networks..."

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INTERNAL_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "An internal error occurred while processing the request"

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Health status of the service
          enum: [healthy, degraded, unhealthy]
          example: "healthy"
        timestamp:
          type: string
          format: date-time
          description: Timestamp when the health check was performed
          example: "2025-12-18T10:00:00Z"
        services:
          type: object
          description: Status of dependent services
          properties:
            qdrant:
              type: string
              enum: [connected, disconnected]
              description: Status of the Qdrant vector database connection
            postgres:
              type: string
              enum: [connected, disconnected]
              description: Status of the Postgres metadata database connection
            gemini:
              type: string
              enum: [connected, disconnected]
              description: Status of the Gemini LLM service connection